### ISSUE TITLE
Stacktrace not detected if HTML encoded

### ISSUE THREAD

**Issue by maa-x** [x41sec/BeanStack#1]
Hi,

First off fantastic extension. I was getting rather tired of doing this by hand..!

I am however having issues with the following response, which is not being parsed by the extension:

```
<H1>Error Page Exception</H1>
<H4>SRVE0260E: The server cannot use the error page specified for your application to handle the Original Exception printed below.</H4>
<BR><H3>Original Exception: </H3>
<B>Error Message: </B>org.springframework.web.util.NestedServletException: Request processing failed&#59; nested exception is com.example.someservice.web.utils.IllegalSessionStateException<BR>
<B>Error Code: </B>500<BR>
<B>Target Servlet: </B>springDialogueFwk<BR>
<B>Error Stack: </B><BR>
com.example.someservice.web.utils.IllegalSessionStateException
<BR>&nbsp;&nbsp;&nbsp;&nbsp;
```

I have attached the [full response](https://github.com/x41sec/BeanStack/files/3734680/test.txt) for ease.

**Comment by luc-x41** [comment]
Apologies Max, we messed up configuring notifications for this repository and I only just saw this. I don't know if this is still relevant for you, but we'll fix this! I should have some time early next week.

**Comment by luc-x41** [comment]
The referenced commit should fix it. Thanks for the report!

I'll do a new release next week after more testing, but for now you can already test the new version if you want to (would be appreciated!) by grabbing the reproducible build from `build/libs/beanstack.jar`. Also feel free to close the ticket if this works and resolves the issue for you :)

**Comment by luc-x41** [comment]
[Released](https://github.com/x41sec/BeanStack/releases/tag/v0.6.0) a patched version
